# -*- coding: utf-8 -*-
"""Seed ship JSON for titans / freighters / sleepers that have model + Echoes portrait."""
from __future__ import annotations

import json
from pathlib import Path

SHIPS = Path(r"H:\game_dev\eveautochess-dev\godot_project\data\ships")

# armor_res from TQ: resonance → resist = 1 - resonance? STATS says 抗性% = (1-resonance)*100
# STATS_TQ stores armor_*_res as resonance multipliers (0.5 = 50% resist)


def star_from_hp(structure, armor, shield=0.0, armor_res=0.5, attack_range=3):
    ar = float(armor_res)
    resist = {"emp": ar, "thermal": ar, "kinetic": ar, "explosive": ar}
    # convert resonance-like to resist fraction used in JSON (Punisher uses 0.5 = 50% resist)
    # STATS_TQ armor_exp_res 0.5 with note 抗性% = (1-resonance)*100 → if stored as resonance 0.5, resist%=50, JSON resist=0.5
    return {
        "attack_range": attack_range,
        "damage": {"emp": 0.0, "thermal": 0.0, "kinetic": 0.0, "explosive": 0.0},
        "repair": {"shield": 0.0, "armor": 0.0, "structure": 0.0},
        "tracking": 0.0,
        "optimal": 0.0,
        "falloff": 0.0,
        "optimal_sig_radius": 0.0,
        "shield_hp": float(shield),
        "armor_hp": float(armor),
        "structure_hp": float(structure),
        "shield_resist": {"emp": 0.0, "thermal": 0.0, "kinetic": 0.0, "explosive": 0.0},
        "armor_resist": dict(resist),
        "structure_resist": {"emp": 0.0, "thermal": 0.0, "kinetic": 0.0, "explosive": 0.0},
        "is_logistic": False,
    }


def write(ship: dict) -> None:
    sid = int(ship["id"])
    path = SHIPS / f"{sid}.json"
    path.write_text(json.dumps(ship, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote", path.name, ship["name"], ship["name_en"])


def main() -> None:
    # --- Titans (CMAG display order in PVP is race pick; ids 201-204 ACGM by MULTIPLAYER table) ---
    titans = [
        {
            "id": 201,
            "name": "圣像级",
            "name_en": "Avatar",
            "type_id": 11567,
            "echoes_item_id": 0,
            "race": "amarr",
            "ship_group": "titan",
            "hull": "at1",
            "model_key": "tq_titan_a",
        },
        {
            "id": 202,
            "name": "利维坦级",
            "name_en": "Leviathan",
            "type_id": 3764,
            "echoes_item_id": 0,
            "race": "caldari",
            "ship_group": "titan",
            "hull": "ct1",
            "model_key": "tq_titan_c",
        },
        {
            "id": 203,
            "name": "厄勒布洛斯级",
            "name_en": "Erebus",
            "type_id": 671,
            "echoes_item_id": 0,
            "race": "gallente",
            "ship_group": "titan",
            "hull": "gt1",
            "model_key": "tq_titan_g",
        },
        {
            "id": 204,
            "name": "诸神黄昏级",
            "name_en": "Ragnarok",
            "type_id": 23773,
            "echoes_item_id": 0,
            "race": "minmatar",
            "ship_group": "titan",
            "hull": "mt1",
            "model_key": "tq_titan_m",
        },
    ]
    for t in titans:
        write(
            {
                **{k: t[k] for k in ("id", "name", "name_en", "type_id", "echoes_item_id", "race", "ship_group", "model_key")},
                "cost": 0,
                "ship_groups": ["titan"],
                "fetter_ids": [t["race"], "titan"],
                "tags": [t["race"], "titan", "nullsec_symbol", "shop_ineligible"],
                "is_logistic": False,
                "weapon_fx": "laser" if t["race"] == "amarr" else "missile" if t["race"] == "caldari" else "rail" if t["race"] == "gallente" else "cannon",
                "shop_eligible": False,
                "signature_radius": 10000.0,
                "sensor_strength": 100.0,
                "scan_resolution": 50.0,
                "speed": 60.0,
                "mass": 2.0e9,
                "agility": 0.1,
                "capacitor_capacity": 100000.0,
                "capacitor_recharge_s": 1000.0,
                "mid_battle_leave_allowed": False,
                "function_slots": {"slots": []},
                "hi_slots": 0,
                "med_slots": 0,
                "low_slots": 0,
                "drone_bandwidth": 0.0,
                "drone_bay_slots": 0,
                "drone_count_cap": 0,
                "attack_cycle_s": 0.0,
                "capital_role": "titan",
                "requires_cyno_entry": False,
                "stars": [star_from_hp(100000, 100000, 100000, 0.5, 0)],  # placeholder; titan_hp from D-EAC-20
                "_stub_note": "nullsec titan symbol; HP authoritative via MULTIPLAYER_PVP titan_hp not ship stars",
            }
        )

    # --- Freighters CMAG ---
    freighters = [
        {
            "id": 211,
            "cmag": "C",
            "name": "渡神级",
            "name_en": "Charon",
            "type_id": 20185,
            "echoes_item_id": 10705000101,
            "race": "caldari",
            "hull": "cfr1",
            "structure": 93000,
            "shield": 60000,
            "armor": 18000,
            "speed": 60,
            "sig": 10660,
            "cap": 3500,
            "cap_s": 215.577,
            "mass": 960000000,
        },
        {
            "id": 212,
            "cmag": "M",
            "name": "芬利厄级",
            "name_en": "Fenrir",
            "type_id": 20189,
            "echoes_item_id": 10705000201,
            "race": "minmatar",
            "hull": "mfr1",
            "structure": 78000,
            "shield": 57600,
            "armor": 26400,
            "speed": 81,
            "sig": 10385,
            "cap": 3000,
            "cap_s": 184.78,
            "mass": 820000000,
        },
        {
            "id": 213,
            "cmag": "A",
            "name": "普罗维登斯级",
            "name_en": "Providence",
            "type_id": 20183,
            "echoes_item_id": 10705000301,
            "race": "amarr",
            "hull": "afr1",
            "structure": 120000,
            "shield": 12000,
            "armor": 55200,
            "speed": 70,
            "sig": 10515,
            "cap": 3750,
            "cap_s": 230.975,
            "mass": 900000000,
        },
        {
            "id": 214,
            "cmag": "G",
            "name": "方尖塔级",
            "name_en": "Obelisk",
            "type_id": 20187,
            "echoes_item_id": 10705000401,
            "race": "gallente",
            "hull": "gfr1",
            "structure": 132000,
            "shield": 16800,
            "armor": 48000,
            "speed": 65,
            "sig": 10605,
            "cap": 3500,
            "cap_s": 215.577,
            "mass": 940000000,
        },
    ]
    for f in freighters:
        write(
            {
                "id": f["id"],
                "name": f["name"],
                "name_en": f["name_en"],
                "type_id": f["type_id"],
                "echoes_item_id": f["echoes_item_id"],
                "cost": 0,
                "race": f["race"],
                "ship_group": "freighter",
                "ship_groups": ["freighter"],
                "model_key": f"tq_freighter_{f['hull']}",
                "fetter_ids": [f["race"], "freighter"],
                "tags": [f["race"], "freighter", "pve_salvage", "shop_ineligible"],
                "is_logistic": False,
                "weapon_fx": "missile",
                "shop_eligible": False,
                "signature_radius": f["sig"],
                "sensor_strength": 0.0,
                "scan_resolution": 0.0,
                "speed": f["speed"],
                "mass": f["mass"],
                "agility": 0.1,
                "capacitor_capacity": f["cap"],
                "capacitor_recharge_s": f["cap_s"],
                "mid_battle_leave_allowed": False,
                "function_slots": {"slots": []},
                "hi_slots": 0,
                "med_slots": 0,
                "low_slots": 0,
                "drone_bandwidth": 0.0,
                "drone_bay_slots": 0,
                "drone_count_cap": 0,
                "attack_cycle_s": 0.0,
                "stars": [star_from_hp(f["structure"], f["armor"], f["shield"], 0.5, 0)],
                "_stub_note": "pve_salvage target; FREIGHTER_AND_TITAN; not shoppable",
            }
        )

    # --- Sleepers: model (TQ threeview ok) + Echoes portrait ---
    sleepers = [
        {
            "id": 221,
            "name": "冬眠者护卫舰A",
            "name_en": "Sleeper Frigate A",
            "type_id": 30216,
            "echoes_item_id": 10100002101,
            "ship_group": "frigate",
            "hull": "slf1",
            "structure": 880,
            "armor": 1760,
            "speed": 2880,
            "sig": 35,
            "cap": 110,
            "cap_s": 500,
            "scan": 1050,
            "mass": 1910000,
            "armor_res": 0.5,
            "weapon_tier": "small",
        },
        {
            "id": 222,
            "name": "冬眠者护卫舰B",
            "name_en": "Sleeper Frigate B",
            "type_id": 30215,
            "echoes_item_id": 10100002102,
            "ship_group": "frigate",
            "hull": "slf2",
            "structure": 1100,
            "armor": 2200,
            "speed": 2610,
            "sig": 35,
            "cap": 110,
            "cap_s": 500,
            "scan": 1000,
            "mass": 1910000,
            "armor_res": 0.4,
            "weapon_tier": "small",
        },
        {
            "id": 223,
            "name": "冬眠者驱逐舰",
            "name_en": "Sleeper Destroyer",
            "type_id": 30208,
            "echoes_item_id": 10200003210,
            "ship_group": "destroyer",
            "hull": "slde1",
            "structure": 4400,
            "armor": 8800,
            "speed": 1485,
            "sig": 150,
            "cap": 725,
            "cap_s": 1000,
            "scan": 350,
            "mass": 10900000,
            "armor_res": 0.4,
            "weapon_tier": "medium",
        },
        {
            "id": 224,
            "name": "冬眠者巡洋舰A",
            "name_en": "Sleeper Cruiser A",
            "type_id": 30206,
            "echoes_item_id": 10300002101,
            "ship_group": "cruiser",
            "hull": "slc1",
            "structure": 5500,
            "armor": 11000,
            "speed": 1800,
            "sig": 150,
            "cap": 725,
            "cap_s": 1000,
            "scan": 340,
            "mass": 10900000,
            "armor_res": 0.3,
            "weapon_tier": "medium",
        },
        {
            "id": 225,
            "name": "冬眠者战列舰A",
            "name_en": "Sleeper Battleship A",
            "type_id": 30196,
            "echoes_item_id": 10500003210,
            "ship_group": "battleship",
            "hull": "slb1",
            "structure": 22000,
            "armor": 44000,
            "speed": 1125,
            "sig": 400,
            "cap": 3300,
            "cap_s": 1000,
            "scan": 130,
            "mass": 19000000,
            "armor_res": 0.35,
            "weapon_tier": "large",
        },
    ]
    # Note: exclude hub; exclude portraits without unique model (10100003210/03212, second cruiser, slb2)
    for s in sleepers:
        write(
            {
                "id": s["id"],
                "name": s["name"],
                "name_en": s["name_en"],
                "type_id": s["type_id"],
                "echoes_item_id": s["echoes_item_id"],
                "cost": 0,
                "race": "sleeper",
                "ship_group": s["ship_group"],
                "ship_groups": [s["ship_group"], "sleeper"],
                "model_key": f"tq_sleeper_{s['hull']}",
                "fetter_ids": ["sleeper", s["ship_group"]],
                "tags": ["sleeper", s["ship_group"], "pve_creep", "shop_ineligible"],
                "is_logistic": False,
                "weapon_fx": "missile",
                "weapon_tier": s["weapon_tier"],
                "shop_eligible": False,
                "signature_radius": s["sig"],
                "sensor_strength": 20.0,
                "scan_resolution": s["scan"],
                "speed": s["speed"],
                "mass": s["mass"],
                "agility": 1.0,
                "capacitor_capacity": s["cap"],
                "capacitor_recharge_s": s["cap_s"],
                "mid_battle_leave_allowed": False,
                "function_slots": {"slots": []},
                "hi_slots": 0,
                "med_slots": 0,
                "low_slots": 0,
                "drone_bandwidth": 0.0,
                "drone_bay_slots": 0,
                "drone_count_cap": 0,
                "attack_cycle_s": 5.0,
                "stars": [star_from_hp(s["structure"], s["armor"], 0.0, s["armor_res"], 3)],
                "_stub_note": "pve_creep_ai unit; requires TQ/Echoes model + Echoes portrait; not shoppable",
            }
        )


if __name__ == "__main__":
    main()
